export const WORDS = [
  { word: "apple", hint: "A common fruit" },
  { word: "banana", hint: "A long yellow fruit" },
  { word: "orange", hint: "A citrus fruit" },
  { word: "cat", hint: "A furry pet that purrs" },
  { word: "dog", hint: "Man's best friend" },
  { word: "fish", hint: "Swims in water" },
  { word: "house", hint: "A place to live" },
  { word: "tree", hint: "Has leaves and branches" },
  { word: "book", hint: "Something you read" },
  { word: "star", hint: "Shines in the night sky" },
  { word: "moon", hint: "Orbits the Earth" },
  { word: "sun", hint: "Our closest star" },
  { word: "bird", hint: "Has feathers and flies" },
  { word: "rain", hint: "Water falling from clouds" },
  { word: "snow", hint: "White and cold, falls in winter" },
  { word: "cloud", hint: "Floats in the sky" },
  { word: "grass", hint: "Covers the ground, green" },
  { word: "river", hint: "Flows towards the sea" },
  { word: "bread", hint: "Baked from flour and yeast" },
  { word: "friend", hint: "Someone you trust and like" },
  { word: "because", hint: "For the reason that" },
  { word: "people", hint: "Human beings, persons" },
  { word: "knight", hint: "A medieval warrior in armor" },
  { word: "ghost", hint: "A spirit of the dead" },
  { word: "thumb", hint: "The short thick finger" },
  { word: "island", hint: "Land surrounded by water" },
  { word: "listen", hint: "Pay attention with your ears" },
  { word: "castle", hint: "A large fortified building" },
  { word: "butter", hint: "Spread on bread or toast" },
  { word: "rabbit", hint: "A small hopping animal with long ears" },
  { word: "middle", hint: "The center of something" },
  { word: "puzzle", hint: "A game or problem to solve" },
  { word: "please", hint: "A polite word used when asking" },
  { word: "enough", hint: "As much as is needed" },
  { word: "through", hint: "From one side to the other" },
  { word: "beautiful", hint: "Very pleasing to look at" },
  { word: "write", hint: "Put words on paper" },
  { word: "quiet", hint: "Making little or no noise" },
  { word: "bridge", hint: "A structure over a river or road" },
  { word: "break", hint: "To split or smash apart" },
  { word: "dream", hint: "Images during sleep, or a wish" },
  { word: "drink", hint: "A liquid you swallow" },
  { word: "brown", hint: "The color of chocolate or wood" },
  { word: "blind", hint: "Unable to see" },
  { word: "build", hint: "To construct or make" },
  { word: "guard", hint: "Someone who protects" },
  { word: "guess", hint: "To try to answer without knowing" },
  { word: "double", hint: "Twice as much, or two of something" },
  { word: "trouble", hint: "A problem or difficulty" },
];

export const SENTENCES = [
  {
    sentence: "the quick brown fox jumps",
    hint: "Contains every letter of the alphabet",
  },
  { sentence: "she sells sea shells", hint: "A famous tongue twister" },
  {
    sentence: "hello world program",
    hint: "Every programmer writes this first",
  },
  { sentence: "learning is fun", hint: "An encouraging phrase" },
  { sentence: "practice makes perfect", hint: "A saying about hard work" },
  { sentence: "a cat sat on the mat", hint: "A simple rhyming sentence" },
  {
    sentence: "peter piper picked a peck of pickled peppers",
    hint: "A tongue twister with many P sounds",
  },
  {
    sentence: "how much wood would a woodchuck chuck",
    hint: "A famous tongue twister about a woodchuck",
  },
  {
    sentence: "big black bugs bleed blue black blood",
    hint: "Hard to say fast, many B sounds",
  },
  {
    sentence: "i saw a saw that could out saw any saw",
    hint: "Same word used as different meanings",
  },
  {
    sentence: "the dog dug a deep damp hole",
    hint: "Many D sounds, watch b and d",
  },
  {
    sentence: "please place the plates on the plain plane",
    hint: "Words that sound the same but differ",
  },
  {
    sentence: "i thought through the tough though thoroughly",
    hint: "Words ending in ough sound different",
  },
  {
    sentence: "my mother made me mash my mangoes",
    hint: "Many M sounds all together",
  },
  {
    sentence: "the queen quietly questioned the quick quark",
    hint: "Lots of Q words to practice",
  },
  {
    sentence: "billy bought bright blue balloons for his birthday",
    hint: "All starts with B, watch the D at the end",
  },
  {
    sentence: "their friends were over there having fun",
    hint: "Commonly confused words their and there",
  },
  {
    sentence: "the night knight knew the knife was not his",
    hint: "Silent K words in a sentence",
  },
];
